countries_list = [
    # Africa
    {"name": "Algeria", "code": "dz", "capital": "Algiers", "population": 43851044, "is_developed": False, "continent": "Africa"},
    {"name": "Angola", "code": "ao", "capital": "Luanda", "population": 32866272, "is_developed": False, "continent": "Africa"},
    {"name": "Benin", "code": "bj", "capital": "Porto-Novo", "population": 12123200, "is_developed": False, "continent": "Africa"},
    {"name": "Botswana", "code": "bw", "capital": "Gaborone", "population": 2351627, "is_developed": False, "continent": "Africa"},
    {"name": "Burkina Faso", "code": "bf", "capital": "Ouagadougou", "population": 20903273, "is_developed": False, "continent": "Africa"},
    {"name": "Burundi", "code": "bi", "capital": "Gitega", "population": 11890784, "is_developed": False, "continent": "Africa"},
    {"name": "Cabo Verde", "code": "cv", "capital": "Praia", "population": 555987, "is_developed": False, "continent": "Africa"},
    {"name": "Cameroon", "code": "cm", "capital": "Yaoundé", "population": 26545863, "is_developed": False, "continent": "Africa"},
    {"name": "Central African Republic", "code": "cf", "capital": "Bangui", "population": 4829767, "is_developed": False, "continent": "Africa"},
    {"name": "Chad", "code": "td", "capital": "N'Djamena", "population": 16425864, "is_developed": False, "continent": "Africa"},
    {"name": "Comoros", "code": "km", "capital": "Moroni", "population": 869601, "is_developed": False, "continent": "Africa"},
    {"name": "Congo, Democratic Republic of the", "code": "cd", "capital": "Kinshasa", "population": 89561403, "is_developed": False, "continent": "Africa"},
    {"name": "Congo, Republic of the", "code": "cg", "capital": "Brazzaville", "population": 5518087, "is_developed": False, "continent": "Africa"},
    {"name": "Cote d'Ivoire", "code": "ci", "capital": "Yamoussoukro", "population": 26378274, "is_developed": False, "continent": "Africa"},
    {"name": "Djibouti", "code": "dj", "capital": "Djibouti", "population": 988000, "is_developed": False, "continent": "Africa"},
    {"name": "Egypt", "code": "eg", "capital": "Cairo", "population": 102334404, "is_developed": False, "continent": "Africa"},
    {"name": "Equatorial Guinea", "code": "gq", "capital": "Malabo", "population": 1402985, "is_developed": False, "continent": "Africa"},
    {"name": "Eritrea", "code": "er", "capital": "Asmara", "population": 3546421, "is_developed": False, "continent": "Africa"},
    {"name": "Eswatini", "code": "sz", "capital": "Mbabane", "population": 1160164, "is_developed": False, "continent": "Africa"},
    {"name": "Ethiopia", "code": "et", "capital": "Addis Ababa", "population": 114963588, "is_developed": False, "continent": "Africa"},
    {"name": "Gabon", "code": "ga", "capital": "Libreville", "population": 2225734, "is_developed": False, "continent": "Africa"},
    {"name": "Gambia", "code": "gm", "capital": "Banjul", "population": 2416668, "is_developed": False, "continent": "Africa"},
    {"name": "Ghana", "code": "gh", "capital": "Accra", "population": 31072940, "is_developed": False, "continent": "Africa"},
    {"name": "Guinea", "code": "gn", "capital": "Conakry", "population": 13132795, "is_developed": False, "continent": "Africa"},
    {"name": "Guinea-Bissau", "code": "gw", "capital": "Bissau", "population": 1968001, "is_developed": False, "continent": "Africa"},
    {"name": "Kenya", "code": "ke", "capital": "Nairobi", "population": 53771296, "is_developed": False, "continent": "Africa"},
    {"name": "Lesotho", "code": "ls", "capital": "Maseru", "population": 2142249, "is_developed": False, "continent": "Africa"},
    {"name": "Liberia", "code": "lr", "capital": "Monrovia", "population": 5057681, "is_developed": False, "continent": "Africa"},
    {"name": "Libya", "code": "ly", "capital": "Tripoli", "population": 6871292, "is_developed": False, "continent": "Africa"},
    {"name": "Madagascar", "code": "mg", "capital": "Antananarivo", "population": 27691018, "is_developed": False, "continent": "Africa"},
    {"name": "Malawi", "code": "mw", "capital": "Lilongwe", "population": 19129952, "is_developed": False, "continent": "Africa"},
    {"name": "Mali", "code": "ml", "capital": "Bamako", "population": 20250833, "is_developed": False, "continent": "Africa"},
    {"name": "Mauritania", "code": "mr", "capital": "Nouakchott", "population": 4649658, "is_developed": False, "continent": "Africa"},
    {"name": "Mauritius", "code": "mu", "capital": "Port Louis", "population": 1271768, "is_developed": False, "continent": "Africa"},
    {"name": "Morocco", "code": "ma", "capital": "Rabat", "population": 36910560, "is_developed": False, "continent": "Africa"},
    {"name": "Mozambique", "code": "mz", "capital": "Maputo", "population": 31255435, "is_developed": False, "continent": "Africa"},
    {"name": "Namibia", "code": "na", "capital": "Windhoek", "population": 2540905, "is_developed": False, "continent": "Africa"},
    {"name": "Niger", "code": "ne", "capital": "Niamey", "population": 24206644, "is_developed": False, "continent": "Africa"},
    {"name": "Nigeria", "code": "ng", "capital": "Abuja", "population": 206139589, "is_developed": False, "continent": "Africa"},
    {"name": "Rwanda", "code": "rw", "capital": "Kigali", "population": 12952218, "is_developed": False, "continent": "Africa"},
    {"name": "Sao Tome and Principe", "code": "st", "capital": "São Tomé", "population": 219159, "is_developed": False, "continent": "Africa"},
    {"name": "Senegal", "code": "sn", "capital": "Dakar", "population": 16743927, "is_developed": False, "continent": "Africa"},
    {"name": "Seychelles", "code": "sc", "capital": "Victoria", "population": 98347, "is_developed": False, "continent": "Africa"},
    {"name": "Sierra Leone", "code": "sl", "capital": "Freetown", "population": 7976983, "is_developed": False, "continent": "Africa"},
    {"name": "Somalia", "code": "so", "capital": "Mogadishu", "population": 15893222, "is_developed": False, "continent": "Africa"},
    {"name": "South Africa", "code": "za", "capital": "Pretoria", "population": 59308690, "is_developed": False, "continent": "Africa"},
    {"name": "South Sudan", "code": "ss", "capital": "Juba", "population": 11193725, "is_developed": False, "continent": "Africa"},
    {"name": "Sudan", "code": "sd", "capital": "Khartoum", "population": 43849260, "is_developed": False, "continent": "Africa"},
    {"name": "Tanzania", "code": "tz", "capital": "Dodoma", "population": 59734218, "is_developed": False, "continent": "Africa"},
    {"name": "Togo", "code": "tg", "capital": "Lomé", "population": 8278724, "is_developed": False, "continent": "Africa"},
    {"name": "Tunisia", "code": "tn", "capital": "Tunis", "population": 11818619, "is_developed": False, "continent": "Africa"},
    {"name": "Uganda", "code": "ug", "capital": "Kampala", "population": 45741007, "is_developed": False, "continent": "Africa"},
    {"name": "Zambia", "code": "zm", "capital": "Lusaka", "population": 18383955, "is_developed": False, "continent": "Africa"},
    {"name": "Zimbabwe", "code": "zw", "capital": "Harare", "population": 14862924, "is_developed": False, "continent": "Africa"},

    # America
    {"name": "Antigua and Barbuda", "code": "ag", "capital": "Saint John's", "population": 97929, "is_developed": False, "continent": "America"},
    {"name": "Argentina", "code": "ar", "capital": "Buenos Aires", "population": 45195774, "is_developed": False, "continent": "America"},
    {"name": "Bahamas", "code": "bs", "capital": "Nassau", "population": 393244, "is_developed": False, "continent": "America"},
    {"name": "Barbados", "code": "bb", "capital": "Bridgetown", "population": 287375, "is_developed": False, "continent": "America"},
    {"name": "Belize", "code": "bz", "capital": "Belmopan", "population": 397628, "is_developed": False, "continent": "America"},
    {"name": "Bolivia", "code": "bo", "capital": "Sucre", "population": 11673021, "is_developed": False, "continent": "America"},
    {"name": "Brazil", "code": "br", "capital": "Brasília", "population": 212559417, "is_developed": False, "continent": "America"},
    {"name": "Canada", "code": "ca", "capital": "Ottawa", "population": 37742154, "is_developed": True, "continent": "America"},
    {"name": "Chile", "code": "cl", "capital": "Santiago", "population": 19116201, "is_developed": True, "continent": "America"},
    {"name": "Colombia", "code": "co", "capital": "Bogotá", "population": 50882891, "is_developed": False, "continent": "America"},
    {"name": "Costa Rica", "code": "cr", "capital": "San José", "population": 5094118, "is_developed": False, "continent": "America"},
    {"name": "Cuba", "code": "cu", "capital": "Havana", "population": 11326616, "is_developed": False, "continent": "America"},
    {"name": "Dominica", "code": "dm", "capital": "Roseau", "population": 71986, "is_developed": False, "continent": "America"},
    {"name": "Dominican Republic", "code": "do", "capital": "Santo Domingo", "population": 10847910, "is_developed": False, "continent": "America"},
    {"name": "Ecuador", "code": "ec", "capital": "Quito", "population": 17643054, "is_developed": False, "continent": "America"},
    {"name": "El Salvador", "code": "sv", "capital": "San Salvador", "population": 6486205, "is_developed": False, "continent": "America"},
    {"name": "Grenada", "code": "gd", "capital": "St. George's", "population": 112523, "is_developed": False, "continent": "America"},
    {"name": "Guatemala", "code": "gt", "capital": "Guatemala City", "population": 17915568, "is_developed": False, "continent": "America"},
    {"name": "Guyana", "code": "gy", "capital": "Georgetown", "population": 786552, "is_developed": False, "continent": "America"},
    {"name": "Haiti", "code": "ht", "capital": "Port-au-Prince", "population": 11402528, "is_developed": False, "continent": "America"},
    {"name": "Honduras", "code": "hn", "capital": "Tegucigalpa", "population": 9904607, "is_developed": False, "continent": "America"},
    {"name": "Jamaica", "code": "jm", "capital": "Kingston", "population": 2961167, "is_developed": False, "continent": "America"},
    {"name": "Mexico", "code": "mx", "capital": "Mexico City", "population": 128932753, "is_developed": False, "continent": "America"},
    {"name": "Nicaragua", "code": "ni", "capital": "Managua", "population": 6624554, "is_developed": False, "continent": "America"},
    {"name": "Panama", "code": "pa", "capital": "Panama City", "population": 4314767, "is_developed": False, "continent": "America"},
    {"name": "Paraguay", "code": "py", "capital": "Asunción", "population": 7132538, "is_developed": False, "continent": "America"},
    {"name": "Peru", "code": "pe", "capital": "Lima", "population": 32971854, "is_developed": False, "continent": "America"},
    {"name": "Saint Kitts and Nevis", "code": "kn", "capital": "Basseterre", "population": 53199, "is_developed": False, "continent": "America"},
    {"name": "Saint Lucia", "code": "lc", "capital": "Castries", "population": 183627, "is_developed": False, "continent": "America"},
    {"name": "Saint Vincent and the Grenadines", "code": "vc", "capital": "Kingstown", "population": 110940, "is_developed": False, "continent": "America"},
    {"name": "Suriname", "code": "sr", "capital": "Paramaribo", "population": 586632, "is_developed": False, "continent": "America"},
    {"name": "Trinidad and Tobago", "code": "tt", "capital": "Port of Spain", "population": 1399488, "is_developed": False, "continent": "America"},
    {"name": "United States", "code": "us", "capital": "Washington, D.C.", "population": 331002651, "is_developed": True, "continent": "America"},
    {"name": "Uruguay", "code": "uy", "capital": "Montevideo", "population": 3473730, "is_developed": False, "continent": "America"},
    {"name": "Venezuela", "code": "ve", "capital": "Caracas", "population": 28435940, "is_developed": False, "continent": "America"},

    # Asia
    {"name": "Afghanistan", "code": "af", "capital": "Kabul", "population": 38928346, "is_developed": False, "continent": "Asia"},
    {"name": "Armenia", "code": "am", "capital": "Yerevan", "population": 2963243, "is_developed": False, "continent": "Asia"},
    {"name": "Azerbaijan", "code": "az", "capital": "Baku", "population": 10139177, "is_developed": False, "continent": "Asia"},
    {"name": "Bahrain", "code": "bh", "capital": "Manama", "population": 1701575, "is_developed": True, "continent": "Asia"},
    {"name": "Bangladesh", "code": "bd", "capital": "Dhaka", "population": 164689383, "is_developed": False, "continent": "Asia"},
    {"name": "Bhutan", "code": "bt", "capital": "Thimphu", "population": 771608, "is_developed": False, "continent": "Asia"},
    {"name": "Brunei", "code": "bn", "capital": "Bandar Seri Begawan", "population": 437479, "is_developed": True, "continent": "Asia"},
    {"name": "Cambodia", "code": "kh", "capital": "Phnom Penh", "population": 16718965, "is_developed": False, "continent": "Asia"},
    {"name": "China", "code": "cn", "capital": "Beijing", "population": 1439323776, "is_developed": False, "continent": "Asia"},
    {"name": "Cyprus", "code": "cy", "capital": "Nicosia", "population": 1207359, "is_developed": True, "continent": "Asia"},
    {"name": "Georgia", "code": "ge", "capital": "Tbilisi", "population": 3989167, "is_developed": False, "continent": "Asia"},
    {"name": "India", "code": "in", "capital": "New Delhi", "population": 1380004385, "is_developed": False, "continent": "Asia"},
    {"name": "Indonesia", "code": "id", "capital": "Jakarta", "population": 273523615, "is_developed": False, "continent": "Asia"},
    {"name": "Iran", "code": "ir", "capital": "Tehran", "population": 83992949, "is_developed": False, "continent": "Asia"},
    {"name": "Iraq", "code": "iq", "capital": "Baghdad", "population": 40222493, "is_developed": False, "continent": "Asia"},
    {"name": "Israel", "code": "il", "capital": "Jerusalem", "population": 8655535, "is_developed": True, "continent": "Asia"},
    {"name": "Japan", "code": "jp", "capital": "Tokyo", "population": 126476461, "is_developed": True, "continent": "Asia"},
    {"name": "Jordan", "code": "jo", "capital": "Amman", "population": 10203134, "is_developed": False, "continent": "Asia"},
    {"name": "Kazakhstan", "code": "kz", "capital": "Nur-Sultan", "population": 18776707, "is_developed": False, "continent": "Asia"},
    {"name": "Kuwait", "code": "kw", "capital": "Kuwait City", "population": 4270571, "is_developed": True, "continent": "Asia"},
    {"name": "Kyrgyzstan", "code": "kg", "capital": "Bishkek", "population": 6524195, "is_developed": False, "continent": "Asia"},
    {"name": "Laos", "code": "la", "capital": "Vientiane", "population": 7275560, "is_developed": False, "continent": "Asia"},
    {"name": "Lebanon", "code": "lb", "capital": "Beirut", "population": 6825445, "is_developed": False, "continent": "Asia"},
    {"name": "Malaysia", "code": "my", "capital": "Kuala Lumpur", "population": 32365999, "is_developed": False, "continent": "Asia"},
    {"name": "Maldives", "code": "mv", "capital": "Malé", "population": 540544, "is_developed": False, "continent": "Asia"},
    {"name": "Mongolia", "code": "mn", "capital": "Ulaanbaatar", "population": 3278290, "is_developed": False, "continent": "Asia"},
    {"name": "Myanmar", "code": "mm", "capital": "Naypyidaw", "population": 54409800, "is_developed": False, "continent": "Asia"},
    {"name": "Nepal", "code": "np", "capital": "Kathmandu", "population": 29136808, "is_developed": False, "continent": "Asia"},
    {"name": "North Korea", "code": "kp", "capital": "Pyongyang", "population": 25778816, "is_developed": False, "continent": "Asia"},
    {"name": "Oman", "code": "om", "capital": "Muscat", "population": 5106626, "is_developed": False, "continent": "Asia"},
    {"name": "Pakistan", "code": "pk", "capital": "Islamabad", "population": 220892340, "is_developed": False, "continent": "Asia"},
    {"name": "Palestine", "code": "ps", "capital": "Ramallah", "population": 5101414, "is_developed": False, "continent": "Asia"},
    {"name": "Philippines", "code": "ph", "capital": "Manila", "population": 109581078, "is_developed": False, "continent": "Asia"},
    {"name": "Qatar", "code": "qa", "capital": "Doha", "population": 2881053, "is_developed": True, "continent": "Asia"},
    {"name": "Saudi Arabia", "code": "sa", "capital": "Riyadh", "population": 34813871, "is_developed": False, "continent": "Asia"},
    {"name": "Singapore", "code": "sg", "capital": "Singapore", "population": 5850342, "is_developed": True, "continent": "Asia"},
    {"name": "South Korea", "code": "kr", "capital": "Seoul", "population": 51269185, "is_developed": True, "continent": "Asia"},
    {"name": "Sri Lanka", "code": "lk", "capital": "Colombo", "population": 21413249, "is_developed": False, "continent": "Asia"},
    {"name": "Syria", "code": "sy", "capital": "Damascus", "population": 17500658, "is_developed": False, "continent": "Asia"},
    {"name": "Taiwan", "code": "tw", "capital": "Taipei", "population": 23816775, "is_developed": True, "continent": "Asia"},
    {"name": "Tajikistan", "code": "tj", "capital": "Dushanbe", "population": 9537645, "is_developed": False, "continent": "Asia"},
    {"name": "Thailand", "code": "th", "capital": "Bangkok", "population": 69799978, "is_developed": False, "continent": "Asia"},
    {"name": "Timor-Leste", "code": "tl", "capital": "Dili", "population": 1318445, "is_developed": False, "continent": "Asia"},
    {"name": "Turkey", "code": "tr", "capital": "Ankara", "population": 84339067, "is_developed": False, "continent": "Asia"},
    {"name": "Turkmenistan", "code": "tm", "capital": "Ashgabat", "population": 6031200, "is_developed": False, "continent": "Asia"},
    {"name": "United Arab Emirates", "code": "ae", "capital": "Abu Dhabi", "population": 9890402, "is_developed": True, "continent": "Asia"},
    {"name": "Uzbekistan", "code": "uz", "capital": "Tashkent", "population": 33469203, "is_developed": False, "continent": "Asia"},
    {"name": "Vietnam", "code": "vn", "capital": "Hanoi", "population": 97338579, "is_developed": False, "continent": "Asia"},
    {"name": "Yemen", "code": "ye", "capital": "Sana'a", "population": 29825964, "is_developed": False, "continent": "Asia"},

    # Europe
    {"name": "Albania", "code": "al", "capital": "Tirana", "population": 2877797, "is_developed": False, "continent": "Europe"},
    {"name": "Andorra", "code": "ad", "capital": "Andorra la Vella", "population": 77265, "is_developed": True, "continent": "Europe"},
    {"name": "Austria", "code": "at", "capital": "Vienna", "population": 9006398, "is_developed": True, "continent": "Europe"},
    {"name": "Belarus", "code": "by", "capital": "Minsk", "population": 9449323, "is_developed": False, "continent": "Europe"},
    {"name": "Belgium", "code": "be", "capital": "Brussels", "population": 11589623, "is_developed": True, "continent": "Europe"},
    {"name": "Bosnia and Herzegovina", "code": "ba", "capital": "Sarajevo", "population": 3280819, "is_developed": False, "continent": "Europe"},
    {"name": "Bulgaria", "code": "bg", "capital": "Sofia", "population": 6948445, "is_developed": False, "continent": "Europe"},
    {"name": "Croatia", "code": "hr", "capital": "Zagreb", "population": 4105267, "is_developed": True, "continent": "Europe"},
    {"name": "Czech Republic", "code": "cz", "capital": "Prague", "population": 10708981, "is_developed": True, "continent": "Europe"},
    {"name": "Denmark", "code": "dk", "capital": "Copenhagen", "population": 5792202, "is_developed": True, "continent": "Europe"},
    {"name": "Estonia", "code": "ee", "capital": "Tallinn", "population": 1326535, "is_developed": True, "continent": "Europe"},
    {"name": "Finland", "code": "fi", "capital": "Helsinki", "population": 5540720, "is_developed": True, "continent": "Europe"},
    {"name": "France", "code": "fr", "capital": "Paris", "population": 65273511, "is_developed": True, "continent": "Europe"},
    {"name": "Germany", "code": "de", "capital": "Berlin", "population": 83783942, "is_developed": True, "continent": "Europe"},
    {"name": "Greece", "code": "gr", "capital": "Athens", "population": 10423054, "is_developed": True, "continent": "Europe"},
    {"name": "Hungary", "code": "hu", "capital": "Budapest", "population": 9660351, "is_developed": True, "continent": "Europe"},
    {"name": "Iceland", "code": "is", "capital": "Reykjavik", "population": 341243, "is_developed": True, "continent": "Europe"},
    {"name": "Ireland", "code": "ie", "capital": "Dublin", "population": 4937786, "is_developed": True, "continent": "Europe"},
    {"name": "Italy", "code": "it", "capital": "Rome", "population": 60461826, "is_developed": True, "continent": "Europe"},
    {"name": "Kosovo", "code": "xk", "capital": "Pristina", "population": 1771234, "is_developed": False, "continent": "Europe"},
    {"name": "Latvia", "code": "lv", "capital": "Riga", "population": 1886198, "is_developed": True, "continent": "Europe"},
    {"name": "Liechtenstein", "code": "li", "capital": "Vaduz", "population": 38128, "is_developed": True, "continent": "Europe"},
    {"name": "Lithuania", "code": "lt", "capital": "Vilnius", "population": 2722289, "is_developed": True, "continent": "Europe"},
    {"name": "Luxembourg", "code": "lu", "capital": "Luxembourg", "population": 625978, "is_developed": True, "continent": "Europe"},
    {"name": "Malta", "code": "mt", "capital": "Valletta", "population": 441543, "is_developed": True, "continent": "Europe"},
    {"name": "Moldova", "code": "md", "capital": "Chișinău", "population": 4033963, "is_developed": False, "continent": "Europe"},
    {"name": "Monaco", "code": "mc", "capital": "Monaco", "population": 39242, "is_developed": True, "continent": "Europe"},
    {"name": "Montenegro", "code": "me", "capital": "Podgorica", "population": 628066, "is_developed": False, "continent": "Europe"},
    {"name": "Netherlands", "code": "nl", "capital": "Amsterdam", "population": 17134872, "is_developed": True, "continent": "Europe"},
    {"name": "North Macedonia", "code": "mk", "capital": "Skopje", "population": 2083374, "is_developed": False, "continent": "Europe"},
    {"name": "Norway", "code": "no", "capital": "Oslo", "population": 5421241, "is_developed": True, "continent": "Europe"},
    {"name": "Poland", "code": "pl", "capital": "Warsaw", "population": 37846611, "is_developed": True, "continent": "Europe"},
    {"name": "Portugal", "code": "pt", "capital": "Lisbon", "population": 10196709, "is_developed": True, "continent": "Europe"},
    {"name": "Romania", "code": "ro", "capital": "Bucharest", "population": 19237691, "is_developed": False, "continent": "Europe"},
    {"name": "Russia", "code": "ru", "capital": "Moscow", "population": 145934462, "is_developed": False, "continent": "Europe"},
    {"name": "San Marino", "code": "sm", "capital": "San Marino", "population": 33931, "is_developed": True, "continent": "Europe"},
    {"name": "Serbia", "code": "rs", "capital": "Belgrade", "population": 8737371, "is_developed": False, "continent": "Europe"},
    {"name": "Slovakia", "code": "sk", "capital": "Bratislava", "population": 5459642, "is_developed": True, "continent": "Europe"},
    {"name": "Slovenia", "code": "si", "capital": "Ljubljana", "population": 2078938, "is_developed": True, "continent": "Europe"},
    {"name": "Spain", "code": "es", "capital": "Madrid", "population": 46754778, "is_developed": True, "continent": "Europe"},
    {"name": "Sweden", "code": "se", "capital": "Stockholm", "population": 10099265, "is_developed": True, "continent": "Europe"},
    {"name": "Switzerland", "code": "ch", "capital": "Bern", "population": 8654622, "is_developed": True, "continent": "Europe"},
    {"name": "Ukraine", "code": "ua", "capital": "Kyiv", "population": 43733762, "is_developed": False, "continent": "Europe"},
    {"name": "United Kingdom", "code": "gb", "capital": "London", "population": 67886011, "is_developed": True, "continent": "Europe"},
    {"name": "Vatican City", "code": "va", "capital": "Vatican City", "population": 801, "is_developed": True, "continent": "Europe"},

    # Oceania
    {"name": "Australia", "code": "au", "capital": "Canberra", "population": 25499884, "is_developed": True, "continent": "Oceania"},
    {"name": "Fiji", "code": "fj", "capital": "Suva", "population": 896445, "is_developed": False, "continent": "Oceania"},
    {"name": "Kiribati", "code": "ki", "capital": "South Tarawa", "population": 119449, "is_developed": False, "continent": "Oceania"},
    {"name": "Marshall Islands", "code": "mh", "capital": "Majuro", "population": 59190, "is_developed": False, "continent": "Oceania"},
    {"name": "Micronesia", "code": "fm", "capital": "Palikir", "population": 115023, "is_developed": False, "continent": "Oceania"},
    {"name": "Nauru", "code": "nr", "capital": "Yaren", "population": 10824, "is_developed": False, "continent": "Oceania"},
    {"name": "New Zealand", "code": "nz", "capital": "Wellington", "population": 4822233, "is_developed": True, "continent": "Oceania"},
    {"name": "Palau", "code": "pw", "capital": "Ngerulmud", "population": 18094, "is_developed": False, "continent": "Oceania"},
    {"name": "Papua New Guinea", "code": "pg", "capital": "Port Moresby", "population": 8947024, "is_developed": False, "continent": "Oceania"},
    {"name": "Samoa", "code": "ws", "capital": "Apia", "population": 198414, "is_developed": False, "continent": "Oceania"},
    {"name": "Solomon Islands", "code": "sb", "capital": "Honiara", "population": 686884, "is_developed": False, "continent": "Oceania"},
    {"name": "Tonga", "code": "to", "capital": "Nuku'alofa", "population": 105695, "is_developed": False, "continent": "Oceania"},
    {"name": "Tuvalu", "code": "tv", "capital": "Funafuti", "population": 11792, "is_developed": False, "continent": "Oceania"},
    {"name": "Vanuatu", "code": "vu", "capital": "Port Vila", "population": 307145, "is_developed": False, "continent": "Oceania"},
]
